### ISSUE TITLE
Enable parinfer on open files

### ISSUE THREAD

**Issue by facundoolano** [oakmac/sublime-text-parinfer#30]
When I start Sublime with some open `.clj` files from a previous session, Parinfer doesn't turn on by default, I have to manually enable it with <kbd>Ctrl</kbd>+<kbd>)</kbd> on each file.

**Comment by ItamarShDev** [comment]
any update on this issue?
Atom-parinfer fixes the file on opening it, and i really miss it on sublime.

If help is needed, ill be glad to try!

**Comment by oakmac** [comment]
I'm not seeing this behavior on my machine.

Can you confirm that `.clj` file extensions are listed when you go to `Preferences > Package Settings > Parinfer` ?

**Comment by ItamarShDev** [comment]
@oakmac yes it is

**Comment by pjago** [comment]
it seems that's the reason: SublimeTextIssues/Core#5
On startup, because the plugin will only load after the view, we can't rely on the event handle on_load.
Looking further, view.begin_edit() was deprecated in ST3, and it is causing a TypeError.

https://github.com/oakmac/sublime-text-parinfer/blob/efc770c81dd847e70162b06a7e44a922fd5735c9/sublime-parinfer.py#L214-L219
